### ISSUE TITLE
Option for cancel link instead of button

### ISSUE THREAD

**Issue by victornamuso** [kindlyops/ember-inline-edit#20]
Would you take a PR for an option that changes the cancel button to a link like in the screenshot below? If so, I forked and completed the code, just need to update the docs and I'll submit the PR. 

<img width="559" alt="tmd_software" src="https://user-images.githubusercontent.com/503585/33054556-f1e4bc9a-ce47-11e7-8445-832636f69255.png">

**Comment by statik** [comment]
sorry it took so long to respond - I'd be open to a PR that made this a configurable option.
