### ISSUE TITLE
'enabled' attribute removes existing text

### ISSUE THREAD

**Issue by BMahabir** [kindlyops/ember-inline-edit#30]
Hi there, thanks for making this wonderful addon.

Currently I am trying to make this component non-editable when certain permissions are enabled in my system.  I noted in the documentation that the `enabled` attribute is likely the way to go for this.  However when set enabled to false, it removes the existing text of the component altogether.  Checking the background HTML, I note that the text is completely gone from the element.  Is there any way to make the component non-editable while still displaying its text?

Please and thanks!

**Comment by swastik** [comment]
I just tried this and I seem to see the text in both normal and block usage. Can you tell me what version you're using please?
